name: "Module-CoreNetworking-Test"
run-name: Core Networking Test Deployment ${{ github.run_id }}
on:
  workflow_dispatch:
    inputs:
      location:
        description: "The location to deploy the test example to."
        required: true
        default: 'uksouth'
        type: choice
        options:
          - 'uksouth'
          - 'ukwest'
  pull_request:
    branches:
      - main

env:
  DEPLOYMENT_FILE: ${{ github.workspace }}/example/example.bicep
  DEPLOYMENT_NAME: Module-CoreNetworking-${{ github.run_id }}
  RESOURCE_GROUP_NAME: corenetwork-${{ github.run_id }}
  DEPLOYMENT_LOCATION: ${{ github.event.inputs.location || 'uksouth' }}
    
jobs:
  Setup:
    runs-on: ubuntu-latest
    outputs:
      deployment_file: ${{ env.DEPLOYMENT_FILE }}
      deployment_name: ${{ env.DEPLOYMENT_NAME }}
      resource_group_name: ${{ env.RESOURCE_GROUP_NAME }}
      deployment_location: ${{ env.DEPLOYMENT_LOCATION }}
    steps:
      - run: echo "Completed Setup"

  Validate:
    needs: [Setup]
    uses: scankin/.github/workflows/bicep-predeploy.yml@main
    with: 
      location: ${{ needs.setup.outputs.deployment_location }}
      deployment_file: ${{ needs.setup.outputs.deployment_file }}
      resource_group_name: ${{ needs.setup.outputs.resource_group_name }}
      deployment_name: ${{ needs.setup.outputs.deployment_name }}
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
      
  Deploy:
    needs: [Setup, Validate]
    uses: scankin/.github/workflows/bicep/bicep-deploy.yml@main
    with:
      location: ${{ needs.setup.outputs.deployment_location }}
      deployment_file: ${{ needs.setup.outputs.deployment_file }}
      resource_group_name: ${{ needs.setup.outputs.resource_group_name }}
      deployment_name: ${{ needs.setup.outputs.deployment_name }}
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}