name: "Module-CoreNetworking-Test"
run-name: Core Networking Test Deployment ${{ github.run_id }}
on:
  workflow_dispatch:
    inputs:
      location:
        description: "The location to deploy the test example to."
        required: true
        default: 'uksouth'
        type: choice
        options:
          - 'uksouth'
          - 'ukwest'
  pull_request:
    branches:
      - main

env:
  DEPLOYMENT_FILE: ${{ github.workspace }}/example/example.bicep
  DEPLOYMENT_NAME: Module-CoreNetworking-${{ github.run_id }}
  RESOURCE_GROUP_NAME: corenetwork-${{ github.run_id }}
  DEPLOYMENT_LOCATION: ${{ github.event.inputs.location || 'uksouth' }}
    
jobs:
  Validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5
      - name: Install AzCLI
        run: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
      - name: Install Bicep
        run: | 
          curl -Lo bicep https://github.com/Azure/bicep/releases/latest/download/bicep-linux-x64
          chmod +x ./bicep
          sudo mv ./bicep /usr/local/bin/bicep
          bicep --help
      - name: Authenticate
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          enable-AzPSSession: true
          auth-type: SERVICE_PRINCIPAL
      - name: Lint
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            az bicep lint --file $DEPLOYMENT_FILE 
      - name: Create Resource Group
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            echo "Resource Group Name is $RESOURCE_GROUP_NAME"
            if [[az group exists --name "$RESOURCE_GROUP_NAME"]]; then
              echo "Resource Group $RESOURCE_GROUP_NAME already exists, skipping creation."
            else
              az group create --name "$RESOURCE_GROUP_NAME" --location "$DEPLOYMENT_LOCATION"
            fi
      - name: Validate
        uses: azure/cli@v2
        with: 
          azcliversion: latest
          inlineScript: |
            az stack group validate --name "$DEPLOYMENT_NAME" \
              --resource-group "$RESOURCE_GROUP_NAME" \
              --action-on-unmanage detachAll \
              --template-file $DEPLOYMENT_FILE \
              --deny-settings-mode None 
      - name: Plan
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            az deployment group what-if --name "$DEPLOYMENT_NAME" \
              --resource-group "$RESOURCE_GROUP_NAME" \
              --template-file $DEPLOYMENT_FILE
      
  Deploy:
    needs: Validate
    uses: scankin/bicep-module-core-networking/.github/workflows/Deploy-Bicep.yml@feature/pipelines
    with:
      location: $DEPLOYMENT_LOCATION
      deployment_file: $DEPLOYMENT_FILE
      resource_group_name: $RESOURCE_GROUP_NAME
      deployment_name: $DEPLOYMENT_NAME

  CleanUp:
    if: ${{ always() && contains(needs.*.result, 'failure')}}
    env:
      DeploymentFile: ${{ github.workspace }}/example/example.bicep
      ResourceGroupName: corenetwork-${{ github.run_id }}
      DeploymentLocation: ${{ github.event.inputs.location || 'uksouth' }}
    runs-on: ubuntu-latest
    steps:
      - name: Install AzCLI
        run: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
      - name: Install Bicep
        run: | 
          curl -Lo bicep https://github.com/Azure/bicep/releases/latest/download/bicep-linux-x64
          chmod +x ./bicep
          sudo mv ./bicep /usr/local/bin/bicep
          bicep --help
      - name: Authenticate
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          enable-AzPSSession: true
          auth-type: SERVICE_PRINCIPAL
      - name: Delete Resource Group
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            echo "Resource Group Name is $RESOURCE_GROUP_NAME"
            if [[az group exists --name "$RESOURCE_GROUP_NAME"]]; then
              echo "Removing Resource Group $RESOURCE_GROUP_NAME"
              az group delete --name "$RESOURCE_GROUP_NAME" --yes
            else
              echo "Resource Group $RESOURCE_GROUP_NAME does not exist, skipping deletion."
            fi